version: '3.8'

x-service: &service
  logging:
    driver: json-file
    options:
      max-size: "100m"
      max-file: "2"
  image: messenger-demo
  restart: always
  entrypoint: ["/bin/bash", "-c"]

services:

  broker:
    <<: *service
    ports:
      - "9001:9001"
    command:
      - >
        node  /mufl/utilities/executables/dist/broker.js
        --host 0.0.0.0 --port 9001 --test_mode --logger_config
        --level DEBUG --print_callstack ERROR --logger_config_end

  web:
    <<: *service
    ports:
      - "8080:8080"
    command:
      - >
          cd /src/web && npm start

